### ISSUE TITLE
Drawings are not centered

### ISSUE THREAD

**Issue by samhenrigold** [samhenrigold/sh.g#4]
it's late and I wanna go to bed but I'm aware this is an issue. I don't know where this is happening, but it's happening somewhere. Again, not a dealbreaker, but it's more of a problem on mobile.

**Comment by gbudjeakp** [comment]
Could you please elaborate a little more?

**Comment by samhenrigold** [comment]
Sure. As the canvas gets more narrow, the Y center point moves up. So on an iPad in landscape, it looks fine. But in portrait, the Y center is stuck in the upper third of the canvas.

**Comment by gbudjeakp** [comment]
Hmmm i see. Do you have a live link to the project? do you mind making a simple ReadMe on how to start the app? That way i can check out the problem.

**Comment by samhenrigold** [comment]
Sure, the site uses 11ty for static rendering but I put it up on Glitch so you don't have to deal with node for this :) https://glitch.com/edit/#!/quilted-seemly-society
